name: hpc-codecov
version: 0.1.0
verbatim:
  cabal-version: '>= 1.10'
license: BSD3
license-file: LICENSE
author:
  - Brandon Chinn <brandon@leapyear.io>
maintainer:
  - Brandon Chinn <brandon@leapyear.io>
category: Control
synopsis: Convert HPC output into Codecov JSON format
description: |
  Convert HPC output into Codecov JSON format.
extra-source-files:
  - README.md
  - CHANGELOG.md

github: LeapYear/hpc-codecov

ghc-options: -Wall
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
  - condition: impl(ghc < 8.8)
    ghc-options:
      - -Wnoncanonical-monadfail-instances

dependencies:
- aeson >= 1.1.2.0 && < 1.5
- base >= 4.9 && < 5
- containers >= 0.5.7.1 && < 0.7
- hpc >= 0.6.0.3 && < 0.7
- text >= 1.2.2.2 && < 1.4

library:
  source-dirs: src

executable:
  source-dirs: exe
  main: Main.hs
  dependencies:
    - bytestring >= 0.10.8.1 && < 0.11
    - hpc-codecov
    - optparse-applicative >= 0.13.2.0 && < 0.16
    - path >= 0.5.13 && < 0.7
    - process >= 1.4.3.0 && < 1.7
    - unordered-containers >= 0.2.8.0 && < 0.3
    - yaml >= 0.8.24 && < 0.12

tests:
  hpc-codecov-test:
    source-dirs:  test
    main:         Main.hs
    dependencies:
      - hpc-codecov
      - tasty
      - tasty-discover
      - tasty-golden
      - tasty-hunit
